title: Ryan Vasquez
description: Alphs template for Jekyll
baseurl: ''

url: 'http://localhost:4000'

facebook: 'https://www.facebook.com/ryanannatuvasquez'
github: 'https://github.com/ryanannatuvasquez'
linkedin: 'https://ph.linkedin.com/in/ryanannatuvasquez'
stackoverflow: 'http://stackoverflow.com/users/4286267/rxv'

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - LICENSE.txt
  - README.md
